# This is a basic workflow to help you get started with Actions

name: cron

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    # Runs at 1am UTC
    - cron: "0 1 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_db:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: start cron
        run: |
            touch .env
            echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
            echo OCTOKIT_TOKEN=${{ secrets.OCTOKIT_TOKEN }} >> .env
            cat .env
            npm start
